# generated by datamodel-codegen:
#   filename:  schema_contacts.json
#   timestamp: 2024-01-20T20:00:16+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field, StrictInt, StrictStr


class ModelItem(BaseModel):
    field_id: StrictStr = Field(..., alias='_id')
    firstName: StrictStr
    lastName: StrictStr
    birthdate: StrictStr
    email: StrictStr
    phone: StrictStr
    street1: StrictStr
    street2: StrictStr
    city: StrictStr
    stateProvince: StrictStr
    postalCode: StrictStr
    country: StrictStr
    owner: StrictStr
    field__v: StrictInt = Field(..., alias='__v')


class Model(BaseModel):
    __root__: List[ModelItem]
