# generated by datamodel-codegen:
#   filename:  schema_user.json
#   timestamp: 2024-01-22T20:03:34+00:00

from __future__ import annotations

from pydantic import BaseModel, Field, StrictInt, StrictStr


class User(BaseModel):
    field_id: StrictStr = Field(..., alias='_id')
    firstName: StrictStr
    lastName: StrictStr
    email: StrictStr
    field__v: StrictInt = Field(..., alias='__v')
